# Generated by Django 4.0.5 on 2022-06-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='mpbile',
            new_name='mobile',
        ),
    ]
